name:                CSE230-final-projects
version:             0.1.0.0
github:              "Molv1659/CSE230-final-project"
license:             BSD3
author:              "Danling Wang, Pengfei Rao, Sicheng Wang, Tianyang Zhou"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/CSE230-final-projects#readme>

dependencies:
- base >= 4.7 && < 5
- network
- network-run
- bytestring
- brick
- vty
- containers
- microlens-th
- microlens

library:
  source-dirs: src

executables:
  CSE230-final-projects-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSE230-final-projects

  BrickTest:
    main:                Main.hs
    source-dirs:         src
    other-modules:       GoLibrary,
                         UI
    ghc-options:
    - -threaded
    - -Wall
    - -Wcompat
    - -O2
    dependencies:
    - CSE230-final-projects

tests:
  CSE230-final-projects-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSE230-final-projects

